export const data = JSON.parse("{\"key\":\"v-bcdbe962\",\"path\":\"/md/python/base/0.%20Anaconda%20%E7%9A%84%E5%8D%B8%E8%BD%BD%E3%80%81%E9%87%8D%E8%A3%85.html\",\"title\":\"0. Anaconda 的卸载与重装指南\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"0. Anaconda 的卸载与重装指南\",\"index\":false,\"description\":\"前言：Python 安装的本质 当我们安装 Python 时，实质上是安装其核心编译器和运行时环境。官网下载的可执行文件（.exe）本质是编译器，核心功能是将代码编译为可执行的字节码。 一、Anaconda 的下载与定位 为什么选择 Anaconda？ 虽然可通过 Python 官网 (https://www.python.org/)直接安装，但 An...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/md/python/base/0.%20Anaconda%20%E7%9A%84%E5%8D%B8%E8%BD%BD%E3%80%81%E9%87%8D%E8%A3%85.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小羊博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"0. Anaconda 的卸载与重装指南\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"前言：Python 安装的本质 当我们安装 Python 时，实质上是安装其核心编译器和运行时环境。官网下载的可执行文件（.exe）本质是编译器，核心功能是将代码编译为可执行的字节码。 一、Anaconda 的下载与定位 为什么选择 Anaconda？ 虽然可通过 Python 官网 (https://www.python.org/)直接安装，但 An...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"喜羊羊\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"0. Anaconda 的卸载与重装指南\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"喜羊羊\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言：Python 安装的本质\",\"slug\":\"前言-python-安装的本质\",\"link\":\"#前言-python-安装的本质\",\"children\":[]},{\"level\":2,\"title\":\"一、Anaconda 的下载与定位\",\"slug\":\"一、anaconda-的下载与定位\",\"link\":\"#一、anaconda-的下载与定位\",\"children\":[{\"level\":3,\"title\":\"为什么选择 Anaconda？\",\"slug\":\"为什么选择-anaconda\",\"link\":\"#为什么选择-anaconda\",\"children\":[]},{\"level\":3,\"title\":\"安装步骤\",\"slug\":\"安装步骤\",\"link\":\"#安装步骤\",\"children\":[]}]},{\"level\":2,\"title\":\"二、彻底卸载 Anaconda\",\"slug\":\"二、彻底卸载-anaconda\",\"link\":\"#二、彻底卸载-anaconda\",\"children\":[]},{\"level\":2,\"title\":\"三、PyCharm 的安装\",\"slug\":\"三、pycharm-的安装\",\"link\":\"#三、pycharm-的安装\",\"children\":[]},{\"level\":2,\"title\":\"四、Jupyter 组件启动问题排查\",\"slug\":\"四、jupyter-组件启动问题排查\",\"link\":\"#四、jupyter-组件启动问题排查\",\"children\":[]},{\"level\":2,\"title\":\"五、修改 Jupyter 默认工作路径\",\"slug\":\"五、修改-jupyter-默认工作路径\",\"link\":\"#五、修改-jupyter-默认工作路径\",\"children\":[]}],\"readingTime\":{\"minutes\":2.07,\"words\":622},\"filePathRelative\":\"md/python/base/0. Anaconda 的卸载、重装.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
